=== phahok/squizze/src/components/squizze/quiz.schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "title": "Quiz",
  "type": "object",
  "properties": {
    "groups": {
      "type": "object",
      "description": "Groups of questions ids separated by type",
      "additionalProperties": {
        "type": "array",
        "items": {
          "type": "integer"
        }
      },
      "uniqueProperties": true,
      "minProperties": 1
    },
    "questions": {
      "description": "List of questions with id and content",
      "type": "array",
      "items": {
        "properties" : {
          "id": {
            "type": "string"
          },
          "content": {
            "type": "string"
          }
        },
        "required": ["id", "content"]
      },
      "uniqueItems": true,
      "minItems": 1
    },
    "summary": {
      "description": "List of possible quiz result groups",
      "type": "object",
      "additionalProperties": {
        "properties" : {
          "longName": {
            "type": "string"
          },
          "rule": {
            "type": "string"
          }
        },
        "required": ["rule"]
      },
      "uniqueItems": true,
      "minItems": 1
    },
    "choices": {
      "description": "Optional list of possible question choices",
      "type": "array",
      "minItems": 1,
      "items": {
        "properties": {
          "value": {
            "type": "integer"
          },
          "content": {
            "type": "string"
          }
        },
        "required": ["value", "content"]
      },
      "uniqueItems": true
    }
  },
  "required": ["summary", "questions", "groups"]
}

=== phahok/squizze/src/quizzes/initial-pokemon/pokemon.quiz.json
{
    "summary":{
        "S": {
          "longName": "Squirtle",
          "rule": "S1 - S2"
        },
        "B": {
          "longName": "Bulbasaur",
          "rule": "B1 - B2"
        },
        "C": {
          "longName": "Charmander",
          "rule": "C1 - C2"
        }
    },
    "choices": [
      {"value": 0, "content": "NÃ£o sei"},
      {"value": 1, "content": "Discordo plenamente"},
      {"value": 2, "content": "Discordo"},
      {"value": 3, "content": "Concordo um pouco"},
      {"value": 4, "content": "Concordo"},
      {"value": 5, "content": "Concordo plenamente"}
    ],
    "groups": {
      "S1": [2],
      "S2": [1],
      "B1": [4],
      "B2": [3],
      "C1": [6],
      "C2": [5]
    },
    "questions": [
        {"id": "1", "content": "Nao gosto de pokemons de agua"},
        {"id": "2", "content": "Gosto de pokemons de agua"},
        {"id": "3", "content": "Nao gosto de pokemons de grama"},
        {"id": "4", "content": "Gosto de pokemons de grama"},
        {"id": "5", "content": "Nao gosto de pokemons de fogo"},
        {"id": "6", "content": "Gosto de pokemons de fogo"}
    ]
}
